@startuml template
autonumber 1.1.1

actor User as u

box "front end"
participant "Item detail page" as detail
end box

box "back end"
participant "CartController" as wc

participant "AddCartProcessor" as addproc

participant "Cart" as cm
end box

database shumishumi as db

u -> detail++ : add to cart
detail -> wc++ : /cart/add
wc -> addproc++ : process

create cm
addproc -> cm++ : new
cm -> db++ : save
return result
return result
return result
return result

@enduml