@startuml template
'autonumber 1.1.1

actor User as u

box "front end"
participant "Cart page" as cart
end box

box "back end"
participant "CartController" as cc

participant "CartUpdateProcessor" as updateproc

participant "Cart" as wm
end box

database shumishumi as db

u -> cart++ : update cart
cart -> cc++ : /cart/update
cc -> updateproc++ : process()

updateproc -> wm++ : update()
wm -> db++ : update()
return result
return result
return result
return result

@enduml