@startuml update item
autonumber 1.1.1

actor User as u

box "front end"
participant "Item Detail page" as detail
participant "Item Update page" as updatepage
end box

box "back end"
participant ItemController as ic
participant ImageController as imc

participant ImageUploadProcessor as upproc
participant ItemupdateProcessor as updateproc

participant Item as im
participant Knowledge as km

participant Image as img
end box

database shumishumi as db

u -> detail++ : click update item
detail -> updatepage --++ : redirect to item update form

autonumber inc a
u -> updatepage : fill out update form
autonumber inc a
u -> updatepage : click update

loop for every image need to be uploaded
updatepage -> imc++ : /image/upload
imc -> upproc++ : process

create img
upproc -> img++ : new
img -> db++ : update
return result
return result
return result
return JSON_RESPONSE
end

autonumber inc b
updatepage -> ic++ : /item/update
ic -> updateproc++ : process

updateproc -> im++ : update
im -> db++ : update
return result

updateproc -> km++ : update
km -> db++ : update
return result
return result

deactivate im

return result
return JSON_RESPONSE

updatepage -> detail++-- : redirect detail page

@enduml