@startuml register

|user|
start
:press register button;
|shumishumi|
:redirect to register page;
|user|
repeat
:fill out register form;
:submit register form;
|shumishumi|
:validate register form;
repeat while (register validation success?) is (no)
-> yes;
:create user;
:send otp email to user;
:redirect to activate page;
|user|
stop
 
@enduml