@startuml forgot password

|user|
start
:open login/register form;
|system|
:redirect to login/register form;
|user|
:click forgot password button;
|system|
:redirect to forgot password form;
|user|
:fillout forgot password form;
:click send request button;
|system|
:create reset password request;
:compose email reset password request;
repeat
|email service|
:send email to user;
|system|
:check if email is successfully send;
backward:repeat request\nin 5 minutes;
repeat while() is (no)
-> yes;
|user|
:open url from email;
:fill out form for reset password;
|system|
:deactivate reset request;
:update user password;
stop

@enduml