@startuml create discussion
'autonumber 1.1.1

actor User as u

box "front end"
participant "Item Detail page" as detail
end box

box "back end"
participant "DiscussionController" as dc

participant "DiscussionDeleteProcessor" as proc
participant "Discussion" as dm
end box

database shumishumi as db

u -> detail++ : delete new discussion
detail -> dc++ : /discussion/delete

dc -> proc++ : process()

proc -> dm++ : delete()
dm -> db++ : delete()
return result
destroy dm
deactivate dm

return result
return JSON_RESPONSE

@enduml