@startuml update discussion
'autonumber 1.1.1

actor User as u

' Box "front end"
participant "Item Detail page" as detail
' end box

' Box "back end"
participant "DiscussionController" as dc

participant "DiscussionUpdateProcessor" as proc
participant "Discussion" as dm
' end box

database shumishumi as db

u -> detail++ : update discussion
detail -> dc++ : /discussion/update

dc -> proc++ : process()

proc -> dm++ : update()
dm -> db++ : save()
return result
return result
return result
return JSON_RESPONSE

@enduml