@startuml add
participant "Frontend" as fe
participant "ItemWishlistController" as iwc

participant "WishlistAddProcessor" as proc

participant "ItemWishlist" as iwm

participant "Activity" as am

database "shumishumi-db" as db

fe -> iwc++ : /item/wishlist/add
iwc -> proc++ : process()

create iwm
proc -> iwm++ : new()
iwm -> iwm : save
iwm -> db : INSERT
deactivate iwm

create am
proc -> am++ : new()
am -> am : save()
am -> db : INSERT
deactivate am

return result
return response

@enduml