@startuml template
'autonumber 1.1.1

actor User as u

' Box "front end"
participant "Cart page" as cart
' end box

participant "Backend" as be

u -> cart++ : update cart
cart -> be++ : /cart/update
return response

@enduml