@startuml pay trx

|user|
start
:pay transaction using midtrans;
|system|
|midtrans|
:proses payment request;
|user|
:click check payment status;
|system|
:consult to midtrans;
|midtrans|
:check payment status;
|system|
:if payment status 
still WAITING_PAYMENT;
if() then(yes)
    stop
else (no)
endif
|system|
:change transaction status\nto ONGOING;
:update displayed status;
stop


@enduml