@startuml query wishlist
'autonumber 1.1.1

actor User as u

' Box "front end"
participant "Home page" as home
participant "Wishlist page" as wishlist
' end box

' Box "back end"
participant WishlistController as wc
participant ImageController as imc

participant WishlistQueryProcessor as wproc
participant ImageDownloadProcessor as downproc

participant User as um
participant UserRole as urm

participant Wishlist as wm
participant Item as im
participant ItemCategory as icm
participant InterestLevel as ilm
participant Hobby as hm

participant Image as img
' end box

database shumishumi as db

u -> home++ : open wishlist page
home -> wishlist --++ : redirect to wishlist page

wishlist -> wc++ : /item/wishlist/query
wc -> wproc++ : process()
wproc -> wm++ : query()
wm -> db++ : query()
return result
return result

wproc -> im++ : query()
loop for every item in result
wproc -> icm++ : query()
icm -> db++: query()
return result

wproc -> ilm++ : query()
ilm -> db++: query()
return result

wproc -> hm++ : query()
hm -> db++: query()
return result
wproc -> um++ : query()
um -> db++: query()
return result
wproc -> im : composeInfo()
wproc <-- im-- : result
deactivate um
deactivate icm
deactivate ilm
deactivate hm

return result
return JSON_RESPONSE

loop for every item in response
    wishlist -> imc++ : /image/download
    imc -> downproc++ : process()
    downproc -> img++ : query()
    img -> db++ : query()
    return result
    return result
    return result
    return BIT_IMAGE
end

@enduml