@startuml remove from wishlist
'autonumber 1.1.1

actor User as u

' Box "front end"
participant "Wishlist page" as wishlist
' end box

' Box "back end"
participant "WishlistController" as wc
participant "WishlistRemoveProcessor" as rmproc
participant Wishlist as wm
' end box

database shumishumi as db

u -> wishlist++ : delete wishlist
wishlist -> wc++ : /item/wishlist/remove
wc -> rmproc++ : process
rmproc -> wm++ : query
wm -> db++ : query
return result
rmproc -> wm : delete
wm -> db++ : delete
return result
deactivate wm
destroy wm

return result
return JSON_RESPONSE

@enduml