@startgantt sprint timeline
[Planning And Requirement Analysis] lasts 7 days
[Definining Requirements] lasts 7 days
[Designing Architecture] lasts 14 days
[Sprint 1] lasts 30 days
[Sprint 2] lasts 30 days

[Sprint 1 planning] lasts 7 days
[FE Development Phase sprint 1] lasts 14 days 
[BE Development Phase sprint 1] lasts 14 days
[Testing Phase sprint 1] lasts 7 days

[Sprint 2 planning] lasts 7 days
[FE Development Phase sprint 2] lasts 14 days 
[BE Development Phase sprint 2] lasts 14 days
[Testing Phase sprint 2] lasts 7 days

Project starts 2023-03-01
[Planning And Requirement Analysis] starts 2023-03-01
[Definining Requirements] starts 2023-03-08
[Designing Architecture] starts 2023-03-15
[Sprint 1] starts 2023-04-01
[Sprint 2] starts 2023-05-01
[Sprint 1 planning] starts 2023-04-01
[FE Development Phase sprint 1] starts 2023-04-08 
[BE Development Phase sprint 1] starts 2023-04-08
[Testing Phase sprint 1] starts 2023-04-22

[Sprint 2 planning] starts 2023-05-01
[FE Development Phase sprint 2] starts 2023-05-08 
[BE Development Phase sprint 2] starts 2023-05-08
[Testing Phase sprint 2] starts 2023-05-22
@endgantt