@startuml usecase diagram

left to right direction

actor User as u

rectangle "Shumishumi"{
    usecase "login" as login
    usecase "register" as register
    usecase "register as merchant" as merchantregister

    usecase "update profile info" as userupdate
    usecase  "forgot password" as password

    usecase "manage item" as merchant1

    usecase "manage wishlist" as wishlist

    usecase "query item" as qitem

    usecase "recommend item" as recommend

    usecase "manage post\ndislike, like, create, update, delete" as post
    usecase "manage comment\ndislike, like, create, update, delete" as comment

    usecase "manage cart" as cart
    usecase "do transaction" as transaction
    usecase "item review" as review
}

actor Merchant as m

u --> login

login -.> qitem : include
qitem <.- recommend : extend

u --> register
u --> merchantregister

u --> userupdate

u --> password

u --> wishlist

u --> post

post -.> comment : extend

u --> cart

u --> transaction
transaction -.> review : include

u <|-- m

m --> merchant1

@enduml