@startuml template
autonumber 1.1.1

actor User as u

box "front end"
participant "Transaction Detail page" as detail
end box

box "back end"
participant "TransactionController" as tc

participant "TransactionFinishProcessor" as finishproc

Participant "Transaction" as trx
participant "Review" as rm
end box

database shumishumi as db

u -> detail++ : press finish button
detail -> tc++ : /transaction/finish

tc -> finishproc++ : process
finishproc -> trx++ : change status to finish

loop for every item in transaction
    create rm
    finishproc -> rm++ : new
    rm -> db++ : create
    return result
    deactivate rm
end

deactivate trx

return result
return JSON_RESPONSE
detail -> detail : reload page

@enduml