@startuml template
'autonumber 1.1.1

actor User as u

box "back end"
participant "TransactionStatusScheduler" as scheduler
participant Transaction as trx
end box

database shumishumi as db

participant Midtrans as mt

u -> mt++ : payTransaction()
mt -> mt : updatePaymentStatus()
deactivate mt

'autonumber inc a
loop for every 5 minute
    activate scheduler
    scheduler -> trx++ : queryTransaction()
    trx -> db++ : query()
    return result
    loop for every transaction in result
        scheduler -> mt++ : checkPaymentStatus()
        return result
        alt if payment status is DONE
            scheduler -> trx : changeTransactionStatus()
            trx -> db++ : update()
            return result
        end
    end

    deactivate trx
end

deactivate scheduler

@enduml