@startuml view transaction detail

|user|
start
:open transaction history list page;
|system|
:redirect to transaction\nhistory list page;
|user|
:click see detail transaction;
|system|
:query transaction detail;
:if transaction status is WAITING_PAYMENT;
if () then (yes)
|midtrans|
:check payment status;
|system|
:if payment status is updated;
if () then (yes)
    :update transaction stautas;
endif
endif

@enduml