@startuml view transaction history

|user|
:open profile dropdown;
:click 'view shopping history' button;
|system|
repeat
:redirect to shopping list page;
:query transaction list;
|user|
:did user want to\nquery with another filter;
backward:adjust transaction filter;
repeat while () is (yes)
-> (no);
stop

@enduml