@startuml see item detail
'autonumber 1.1.1

actor User as u

box "front end"
participant "Home page" as home
participant "Item detail page" as detail
end box

box "back end"
participant "ItemController" as ic
participant "ImageController" as imc

participant "ImageDownloadProcessor" as downproc
participant "ItemQueryDetailProcessors" as detailproc

participant "Item" as im
participant ItemCategory as icm
participant InterestLevel as ilm
participant Hobby as hm
participant User as um
participant Activity as am

participant "Image" as img
end box

database shumishumi as db

u -> home++ : click item card
home -> detail --++ : redirect to item detail page
detail -> ic++ : /item/query/detail
ic -> detailproc++ : process()
detailproc -> im++ : query()
im -> db++ : query()
return result

detailproc -> icm++ : query()
icm -> db++: query()
return result

detailproc -> ilm++ : query()
ilm -> db++: query()
return result

detailproc -> hm++ : query()
hm -> db++: query()
return result
detailproc -> um++ : query()
um -> db++: query()
return result

detailproc -> im : composeInfo()
deactivate um
deactivate icm
deactivate ilm
deactivate hm

return result

create am
detailproc -> am++ : new()
am -> db++ : create()
return result
return result

return result
return JSON_RESPONSE

'autonumber inc b
loop for every image in item
    detail -> imc++ : /image/download
    imc -> downproc++ : process()
    downproc -> img++ : query()
    img -> db++ : query()
    return result
    return result
    return result
    return BIT_IMAGE
end

@enduml