@startuml view merchant page
autonumber 1.1.1

actor User as u

box "front end"
participant "Item detail page" as detail
participant "Merchant page" as merchant
end box

box "back end"
participant UserController as uc
participant ItemController as ic
participant ImageController as imc

participant UserQueryProcessor as userproc
participant ItemQueryProcessor as itemproc
participant ImageDownloadProcessor as downproc

participant User as um
participant UserRole as urm

participant Item as im
participant ItemCategory as icm
participant InterestLevel as ilm
participant Hobby as hm

participant Image as img
end box

database shumishumi as db

u -> detail++ : open merchant info page
detail -> merchant --++ : redirect to merchant info page

merchant -> uc++ : /user/info
uc -> userproc++ : process
userproc -> um++ : query
um -> db++ : query
return result

userproc -> urm++ : query
urm -> db++ : query
return result
return result
return result
return result
return JSON_RESPONSE

merchant -> ic++ : /item/query
ic -> itemproc++ : proc

itemproc -> im++ : query
loop for every item in result
itemproc -> icm++ : query
icm -> db++: query
return result

itemproc -> ilm++ : query
ilm -> db++: query
return result

itemproc -> hm++ : query
hm -> db++: query
return result
itemproc -> um++ : query
um -> db++: query
return result

itemproc -> im : compose neccessary info
deactivate um
deactivate icm
deactivate ilm
deactivate hm
end

return result
return result
return JSON_RESPONSE

loop for every item in response
    merchant -> imc++ : /image/download
    imc -> downproc++ : process
    downproc -> img++ : query
    img -> db++ : query
    return result
    return result
    return result
    return BIT_IMAGE
end

@enduml