@startuml activate
'autonumber 1.1.1

actor User as u

box "front end"
participant "Register page" as register
participant "Activate Page" as active
participant "Login Page" as login
end box
box "back end"
participant "UserController" as userc

participant "EmailDecryptProcessor" as decproc

participant "UserActivateProcessor" as proc

participant "EmailEncrypt" as eem
participant "User" as um
participant "Otp" as om
end box

database shumishumi as db

u -> register++ : register processor
register -> register : finish register
register -> active--++ : redirect to activate page\nwith encrypted email


active -> userc++ : /user/email/decrypt
userc -> decproc++ : process()
decproc -> eem++ : query()
eem -> db++ : query()
return result
return result
decproc -> eem !! : disable()

return result
return JSON_RESPONSE

'autonumber inc a
u -> active : fill out activate user form
'autonumber inc a
u -> active : click submit

active -> userc++ : /user/activate
userc -> proc++ : process()

proc -> um++ : queryByEmail()
um -> db++ : query()
return result
proc <-- um : result()

proc -> um : setStatus()
proc -> um : update()
um -> db++ : update()
return result
return result
return result

return JSON_RESPONSE

active -> login--++ : redirect to login page

@enduml