@startuml template
autonumber 1.1.1

actor User as u

box "front end"
participant "Home page" as home
participant "User info page" as uinfo
end box

box "back end"
participant "ImageController" as ic
participant "UserController" as uc
participant "ImageDownloadProcessor" as downproc
participant "UserQueryProcessor" as queproc

participant "User" as um
participant "Image" as im
participant "UserRole" as urm
end box

database shumishumi as db

u -> home++ : click user info page
home -> uinfo ++-- : redirect to user info page

uinfo -> uc++ : /user/info
uc -> queproc++ : process
queproc -> um++ : query
um -> db++ : query
return result
queproc -> urm++ : query
urm -> db++ : query
return result
return result
queproc -> um : compose role into user
return result

return result
return result

autonumber inc b
uinfo -> ic++ : /image/download
ic -> downproc++ : process
downproc -> im++ : query
im -> db++ : query
return result
return result
return result
return IMAGE_BIT
@enduml