@startuml update user info
'autonumber 1.1.1

actor User as u

box "front end"
participant "User info page" as uinfo
participant "Update user info page" as update
end box

box "back end"
participant "ImageController" as ic
participant "UserController" as uc
participant "UserUpdateProcessor" as updproc

participant "User" as um
participant "Image" as im
end box

database shumishumi as db

u -> uinfo : click update user info
uinfo -> update --++ : redirect to update form

'autonumber inc a
u -> update : fill out update form

'autonumber inc a
u -> update : click submit button

update -> uc++ : /user/update
uc -> updproc++ : process()

alt if there is any update to image
create im
updproc -> im++ : new()
im -> db++ : save()
return result
return result
end

updproc -> um++ : update()
um -> db++: update()
return result
return result
return result

return JSON_RESULT

update --> uinfo ++-- : redirect to user info page

@enduml