@startuml forgot password
'autonumber 1.1.1

actor User as u

box "front end"
participant "Login Page" as login
participant "Forgot Password page" as forgot
participant "Reset Password page" as reset
end box

box "back end"
participant "UserController" as uc

participant "ForgotPasswordProcessor" as sendproc
participant "ForgotPasswordQueryProcessor" as queryproc
participant "ResetPasswordProcessor" as resetproc

participant "ResetPassword" as rpm
participant "User" as um

participant "Content" as cm
end box

database shumishumi as db

u -> login++ : click forgot password button
login -> forgot --++ : redirect to forgot page

'autonumber inc a
u -> forgot : fill out form
'autonumber inc a
u -> forgot : click submit button

forgot -> uc++ : /user/forgot_password/send

uc -> sendproc++ : process()
create rpm
sendproc -> rpm++ : new()
rpm -> db++ : save()
return result
return result

sendproc -> cm++ : query()
cm -> db++ : query()
return result
return result

sendproc -> sendproc : composeEmail()
loop if send email process not success
sendproc -> sendproc : sendEmail();
u <-- sendproc : send email
end

return result
return result

deactivate forgot

'autonumber inc a
u -> reset++ : open url from email
reset -> uc++ : /user/forgot_password/query
uc -> queryproc++ : process
queryproc -> rpm++ : query
rpm -> db++ : query
return result
queryproc <-- rpm : result
queryproc --> rpm !! : delete
deactivate rpm

return result
return JSON_RESPONSE

'autonumber inc a
u -> reset : fill out reset password form
'autonumber inc a
u -> reset : click submit button

reset -> uc++ : /user/reset_password
uc -> resetproc++ : process

resetproc -> um++ : query
um -> db++ : query
return result
resetproc -> um : update password
um -> db++ : update
return result
return result

return result
return JSON_RESPONSE

reset --> login --++ : redirect to login page

@enduml