@startuml become a merchant
'autonumber 1.1.1

actor User as u

' Box "front end"
participant "Home page" as home
' end box

' Box "back end"
participant "UserController" as uc
participant "MerchantApplyProcessor" as applyproc

participant "User" as um
' end box

database shumishumi as db

u -> home++ : click 'become a merchant' button
home -> uc++ : /user/merchant/apply
uc -> applyproc++ : process()
applyproc -> um++ : query()
um -> db++ : query()
return result

applyproc -> um : updateRole()
um -> db++ : update()
return result
return result

return result

return JSON_RESPONSE

home -> home : reload page

@enduml