@startuml forgot password
'autonumber 1.1.1

actor User as u

' Box "front end"
participant "Login Page" as login
participant "Forgot Password page" as forgot
participant "Reset Password page" as reset
' end box

participant "Backend" as be

u -> login++ : click forgot password button
login -> forgot --++ : redirect to forgot page
u -> forgot : fill out form
u -> forgot : click submit button

forgot -> be++ : /user/forgot_password/send
return response

deactivate forgot

'autonumber inc a
u -> reset++ : open url from email
reset -> be++ : /user/forgot_password/query
return response

u -> reset : fill out reset password form
u -> reset : click submit button

reset -> be++ : /user/reset_password
return response

reset --> login --++ : redirect to login page

@enduml