@startuml template
'autonumber 1.1.1

actor User as u

' Box "front end"
participant "Transaction Detail page" as detail
' end box

participant "Backend" as be

u -> detail++ : press finish button
detail -> be++ : /transaction/cancel
return response
detail -> detail : reload page

@enduml