@startuml pay trx

|user|
start
:pay transaction using midtrans;
|midtrans|
:proses payment request;
|user|
:click check payment status;
|system|
:consult to midtrans;
|midtrans|
:check payment status;
if() then(still waiting for payment)
stop
endif
|system|
:create activity record;
:change transaction status\nto ONGOING;
:update displayed status;
stop


@enduml