@startuml add to wishlist
'autonumber 1.1.1

actor User as u

' Box "front end"
participant "Item Detail Page" as detail
' end box

' Box "back end"
participant "WishlistController" as wc
participant "AddWishlishProcessor" as proc

participant "Wishlist" as w
participant "Activity" as am
' end box

database shumishumi as db

u -> detail++ : click add to wishlist
detail -> wc++ : /item/wishlist/add
wc -> proc++ : process()

create w
proc -> w++ : new()
w -> db++ : create()
return result

create am
proc -> am++ : new()
am -> db++ : create()
return result
return result
return result
return result
return JSON_RESULT

@enduml