@startuml forgotPassword
participant "Frontend" as fe
participant "UserController" as uc

participant "ForgotPasswordProcessor" as proc

participant "User" as um
participant "Dictionary" as dictm
participant "ResetPassword" as rpm

database "shumishumi-db" as db

fe -> uc++ : /user/forgot_password/send
uc -> proc++ : process()
proc -> um++ : queryByEmail()
um -> db : SELECT
return user model

proc -> dictm++ : queryByKey()
dictm -> db : SELECT
return dictionary model

create rpm
proc -> rpm++ : new()
rpm -> rpm : save()
rpm -> db : INSERT
deactivate rpm

proc -> proc : sendEmail()

return result
return response

@enduml
