@startuml forgotPasswordQuery
participant "Frontend" as fe
participant "UserController" as uc

participant "ForgotPasswordQueryProcessor" as proc

participant "ResetPassword" as rpm

database "shumishumi-db" as db

fe -> uc++ : /user/forgot_password/query
uc -> proc++ : process()

proc -> rpm++ : queryByUuid()
rpm -> db : SELECT
proc <-- rpm : reset password model
proc -> rpm : invalidate()
deactivate rpm

return result
return response

@enduml
