@startuml see item detail
|user|
:click item card;
|system|
:query item detail;
:check if user login;
if () then (yes)
    :create activity record;
else (no)
endif
:redirect to item detail page;
stop
@enduml