@startuml see item detail
|user|
:click item card;
|system|
:query item detail;
:check if user login;
if () then (yes)
:create activity record;
else (no)
    :redirect to item detail page;
endif
stop
@enduml