@startuml update
participant "Frontend" as fe
participant "CartController" as cc

participant "CartUpdateProcessor" as proc

participant "Cart" as cm

database "shumishumi-db" as db

fe -> cc++ : /cart/update
cc -> proc++ : process()

proc -> cm++ : queryByUserIdAndItemId()
cm -> db: SELECT
proc <-- cm : cart model

proc -> cm : updateQuantity()
cm -> db : UPDATE
deactivate cm

return result
return response

@enduml
