@startuml forgot - reset password user flow

Actor User as u

box "Frontend"
Participant "Login Page \n<color:red>/login" as login
Participant "Forgot Password page \n<color:red>/user/forgot" as forgot
Participant "Reset Password Page \n<color:red>/user/reset" as reset
end box

box "Backend" #LightBlue
Participant "Backend" as be
Participant "Mysql" as db
end box

u -> login : click reset password
login -> forgot : redirect to forgot page
forgot -> be : <color:red>/user/forgot_password/send
note left
    Request:
    - email user
end note
be -> db : insert reset_password
note left
    Field:
    - uuid
    - email
    - expired time
    - is_active
end note
be -> be : generate link
note left
    <url>/user/reset?q=uuid
end note
u <-- be : send email
note right
    FE need to create new email template
    and insert it to DB
    table: content
end note
u -> u : open email
u -> reset : open
reset -> be : <color:red>/user/forgot_password/query
note left
    Request:
    - uuid
end note
be -> db : query by email
return result
reset <-- be : return result
note left
    result: 
    - email
end note
u -> reset : fill out form
reset -> be : <color:red>/user/reset_password
note left
    Request:
    - email
    - password
    - confirm password
end note
be -> db : query user by email
return user
be -> db : deactivate reset_password by email
return result
be -> be : validate
note left #Pink
    - expired time more than now
    - is_active is still true
end note
be -> db : update user password
return result
reset <-- be : result
u <-- reset : show success message
reset -> u : prompt to redirect to login page

@enduml